### ISSUE TITLE
Extra properties rendered in ParameterValue

### ISSUE THREAD

**Issue by jakebeal** [SD2E/opil#137]
In the ParameterValue diagram, there are extra instances of the properties showing up, an these extra instances have the wrong cardinality.

- ParameterValue should not be showing an unbounded hasMeasure
- The subclasses should not be showing an unbounded valueOf

**Comment by bbartley** [comment]
These are fixed in a2f1bf16 and 1e8cb765f respectively, but there also appears to be an issue with the inheritance arc being doubled:
[URIValue_abstraction_hierarchy.pdf](https://github.com/SD2E/opil/files/6006536/URIValue_abstraction_hierarchy.pdf)
This can maybe patched by using the "concentrate" option on a graphviz graph object, which merges redundant arrows
